/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    "./app/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
      height: {
        900: "900px",
      },
      width: {
        footerSvg: "90rem",
        breadcrumWidth: "400px",
        popover: "600px",
      },
      colors: {
        primary1: "#8447E9",
        primary2: "#5C51A0",
        secondary1: "#5683C3",
        secondary2: "#FCFAFF",
        background: "#FCFAFF",
        mainBg: "#FFFFFF",
        ptColor: "#757575",
        footerBg: "#4C0082",
        footerBanner: "#F6F6F6",
        footerBannerText: "#919191",
        heroBg: "#51018A",
        menuTitle: "#4C0082",
        tabColor: "#F7F1FF",
        gradientColor1: "#8447E9",
        gradientColor2: "#3E76FF",
        gradientColor3: "#FF3EB9",
        requestConsultationBg: "#FCFAFF",
        gradientButtonColor: "#00000040",
        cardViewBg: "#F8F3FF",
        grayColor: "#979797",
        spinnerGreenText: "#37BDBC",
        spinnerYellowText: "#E7B468",
        spinnerRedText: "#EB5A45",
        spinnerBlueText: "#7FB6E6",
        spinnerDescription: "#383D4A",
        footerBannerShadow: "#FFB600",
        footerBannerShadow: "#FFB600",
        footerBannerShadow: "#FFB600",
        blurColor: "#909090",
        cardViewParaText: "#8A8A8A",
        countUpText: "#FFFEFE",
        jobDetailText: "#929292",
        applyNow: "#3671E9",
        core1: "#9B11B1",
        core2: "#FFB600",
        core3: "#8447E9",
        core4: "#4B0281",
        core5: "#384E85",
        core6: "#3A63A9",
        sliderSecondary: "#B7B4B4",
        paragraph: "#242424",
        input: "#959595",
        inputBg: "rgba(217, 217, 217, 0.2)",
        inputPh: "#959595",
        blueLight: "#8447E9",
        blueDark: "#483EA8",
        orange_primary: "#FF725E",
        transLine: "#F3F3F3",
      },
      fontFamily: {
        salsa: ["Salsa"],
        rubik: ["Rubik", "sans-serif"],
        lemon_milk: ["lemon milk"],
      },
      fontSize: {
        "salsa-sm": "28.3389px",
        "rubik-lg": "31.2029px",
        md: ["18px", "17px"],
      },
      lineHeight: {
        "salsa-sm": "35px",
        "rubik-lg": "37px",
      },
      letterSpacing: {
        "salsa-wide": "0.17em",
        "rubik-narrow": "0.03em",
      },
      margin: {
        "23rem": "23rem",
        "28rem": "28rem",
      },
      backgroundImage: () => ({
        hero: "url('/assets/Services.gif')",
        menuBg: "url('/assets/MenuBg.svg')",
        spinnerBg: "url('/assets/spinnerBg.svg')",
        spinnerRed: "url('/assets/spinnerRed.svg')",
        spinnerYellow: "url('/assets/spinnerYellow.svg')",
        spinnerGreen: "url('/assets/spinnerGreen.svg')",
        spinnerBlue: "url('/assets/spinnerBlue.svg')",
        partnersBg: "url('/assets/Bg.svg')",
        stackBg: "url('/assets/stack/stack_bg.svg')",
        contactBg: "url('/assets/services/contact_bg.svg')",
        portBg: "url('/assests/portfolio/portBg.svg')",
        quoteBg: "url('/assests/quote/quoteBg.png')",
        footerContactUsBanner: "url('/assets/footerBanner.svg')",
        careerPageBg: "url('/assets/careers/careerPageBg.svg')",
      }),
      borderWidth: {
        3: "3px",
      },
    },
  },
  variants: {
    extend: {
      cursor: ["hover", "focus"],
      extend: {
        ringWidth: ["focus-visible"],
      },
      focusVisible: [],
    },
  },
  plugins: [
    // require('tailwindcss-border-gradients'),
    // other plugins...
  ],
};
